# Add "approved" label to PRs with at least 1 approving reviewer
on: pull_request
name: eslint check all request
jobs:
  eslintcheck:
    name: ESLint checks
    runs-on: ubuntu-latest
    steps:
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
